all: basic-example duration-example basic-modal-example

basic-example:
	cd .. && elm make examples/Basic/Main.elm --output=examples/Compiled/basic.js

duration-example:
	cd .. && elm make examples/Duration/Main.elm --output=examples/Compiled/duration.js

basic-modal-example:
	cd .. && elm make examples/BasicModal/Main.elm --output=examples/Compiled/basic-modal.js